#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage:
  scripts/update_discussion_index.sh [--output docs/discussion_index.md]

Behavior:
  - Scans bridge/index.md for bridge discussion threads
  - Scans outputs/*_debate directories
  - Scans queue/reports for debate/review discussion reports
  - Writes a consolidated discussion index markdown
USAGE
}

output_file="docs/discussion_index.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) output_file="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

mkdir -p "$(dirname "$output_file")"

now="$(date '+%Y-%m-%dT%H:%M:%S%z')"

bridge_rows=""
if [[ -f bridge/index.md ]]; then
  bridge_rows="$(awk -F'|' '
    /^\|[[:space:]]*bridge_[0-9]+[[:space:]]*\|/ {
      task=$2; gsub(/^[[:space:]]+|[[:space:]]+$/, "", task)
      owner=$3; gsub(/^[[:space:]]+|[[:space:]]+$/, "", owner)
      st=$4; gsub(/^[[:space:]]+|[[:space:]]+$/, "", st)
      updated=$5; gsub(/^[[:space:]]+|[[:space:]]+$/, "", updated)
      latest=$6; gsub(/^[[:space:]]+|[[:space:]]+$/, "", latest)
      if (task != "" && task ~ /^bridge_[0-9]+$/) {
        print "| " task " | " owner " | " st " | " updated " | bridge/" latest " |"
      }
    }
  ' bridge/index.md | sort)"
fi

output_rows=""
if [[ -d outputs ]]; then
  output_rows="$(find outputs -maxdepth 1 -type d -name '*_debate' | sort | while read -r d; do
    files="$(find "$d" -maxdepth 1 -type f -name '*.md' | wc -l)"
    latest="$(find "$d" -maxdepth 1 -type f -name '*.md' -printf '%TY-%Tm-%TdT%TH:%TM %p\n' 2>/dev/null | sort -r | head -n 1 | awk '{print $1 " " $2}')"
    [[ -z "$latest" ]] && latest="-"
    name="$(basename "$d")"
    echo "| ${name} | ${files} | ${latest} | ${d} |"
  done)"
fi

report_rows=""
report_rows="$(find queue/reports -maxdepth 1 -type f \
  \( -name '*bridge*report.yaml' -o -name '*debate*report.yaml' -o -name '*tradeoff*report.yaml' -o -name '*system_improvement*report.yaml' \) \
  -printf '%TY-%Tm-%TdT%TH:%TM %p\n' 2>/dev/null | sort -r | head -n 30 | awk '{print "| " $1 " | " $2 " |"}')"

active_rows=""
active_rows="$(find queue/tasks -maxdepth 1 -type f -name 'worker*.yaml' -print0 | xargs -0 awk '
  /task_id:/ {tid=$2}
  /parent_cmd:/ {pcmd=$2}
  /status:/ {st=$2}
  /timestamp:/ {ts=$2}
  END {}
  {
    if ($1=="task_id:") tid=$2
    if ($1=="parent_cmd:") pcmd=$2
    if ($1=="status:") st=$2
    if ($1=="timestamp:") ts=$2
  }
  FNR==NR {next}
' 2>/dev/null || true)"

{
  echo "# Discussion Index"
  echo "updated_at: ${now}"
  echo
  echo "## Active Discussion Tasks"
  echo "| worker_task | parent_cmd | status | task_file |"
  echo "|---|---|---|---|"
  for f in queue/tasks/worker*.yaml; do
    [[ -f "$f" ]] || continue
    tid="$(awk '/task_id:/ {print $2; exit}' "$f")"
    pcmd="$(awk '/parent_cmd:/ {print $2; exit}' "$f")"
    st="$(awk '/status:/ {print $2; exit}' "$f")"
    if [[ "$st" == "assigned" || "$st" == "in_progress" ]]; then
      echo "| ${tid:--} | ${pcmd:--} | ${st:--} | ${f} |"
    fi
  done
  echo
  echo "## Bridge Threads"
  echo "| task_id | owner | status | updated_at | latest_file |"
  echo "|---|---|---|---|---|"
  if [[ -n "$bridge_rows" ]]; then
    echo "$bridge_rows"
  else
    echo "| - | - | - | - | - |"
  fi
  echo
  echo "## Debate Output Bundles"
  echo "| bundle | files | latest | path |"
  echo "|---|---|---|---|"
  if [[ -n "$output_rows" ]]; then
    echo "$output_rows"
  else
    echo "| - | - | - | - |"
  fi
  echo
  echo "## Recent Discussion Reports"
  echo "| timestamp | report_file |"
  echo "|---|---|"
  if [[ -n "$report_rows" ]]; then
    echo "$report_rows"
  else
    echo "| - | - |"
  fi
  echo
  echo "## Notes"
  echo "- This file is generated by scripts/update_discussion_index.sh."
  echo "- Re-run after major bridge debates or worker discussion rounds."
} > "$output_file"

echo "discussion_index_updated|file=${output_file}"
